### PR TITLE
Better build, better linux support and enable coin

### PR DESCRIPTION
**Pull request by stormckey**
`set_shadow` is not available on linux
And the former bottom bar may align weirdly when the window expands.
Now the coin button on the left-bottom can work properly.

### CODE REVIEW

**Review by awkj — COMMENTED** [review]
thanks !

**Review by awkj — COMMENTED** [review]
good , wait tauri 2.0 release, will big update for it

**Comment by awkj** [comment]
can you add a auto task to build mac/windows/linux release , use github action ?

**Comment by stormckey** [comment]
Done, see the new pr #7

**Pull request merged**
